name: 'bmqy'

on:
  push:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  stale:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          # in this example, there is a newer version already installed, 3.7.7, so the older version will be downloaded
          operating-system: ['ubuntu-latest']
      steps:
        - name: Run with setup-python 3.9
            uses: actions/setup-python@v4
            with:
            python-version: '3.9'
            update-environment: false
            cache: 'pipenv'
        - name: Install pipenv
            run: pip3 install --user pipenv
        - name: Install dependecies
            run:  pipenv --python python3 && pipenv install
        - name: Build
            run: pipenv run build
        - name: Commit and push if changed   # 更新README.md
            run: |
            git diff
            git config --global user.email "qq88268459@126.com"
            git config --global user.name "bmqy"
            git add README.md
            git commit -m "Github Action Auto Updated"
            git push
